CREATE TABLE
    TM_INSURANCE_PLAN
    (
        INSURANCE_ID INTEGER NOT NULL AUTO_INCREMENT,
        INSURANCE_PRODUCT CHARACTER(20) NOT NULL,
        INSURANCE_COMPANY VARCHAR(20),
        INSURANCE_LINK VARCHAR(50),
        INVEST_PERCENT INTEGER,
        INVEST_CURR DECIMAL(15,2),
        CREATED_TIME TIMESTAMP,
        PRIMARY KEY (INSURANCE_ID)
    );
